AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  anlessini-SAM

  Sample SAM Template for anlessini-SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  SearchLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SearchLambdaFunction
      Handler: io.anlessini.SearchLambda::handleRequest
      Runtime: java11
      MemorySize: 3008
      Policies:
        - S3ReadPolicy:
            BucketName: '*'
        - DynamoDBCrudPolicy:
            TableName: '*'
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          INDEX_BUCKET: acl-lucene-index
          INDEX_KEY: acl
      Events:
        AnlessiniSearch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /search
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AnlessiniAPI:
    Description: "API Gateway endpoint URL for Prod stage for search lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/"
  SearchLambdaFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt SearchLambdaFunction.Arn
  SearchLambdaFunctionIamRole:
    Description: "Implicit IAM Role created for search lambda function"
    Value: !GetAtt SearchLambdaFunction.Arn
